

class AbstractSensor:

    """
    Holds the minimum requirement a sensor has to fulfil
    
    value holds the most recent value generated by the sensor
     -> to be updated by the sensor which must implement an update() method
    """
    def __init__(self):
        self.value = None
